services:
  - type: web
    name: investiq-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libmagic-dev
      pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10
    envVars:
      - key: PORT
        value: 10000
